[package]
name = "sdkwork-api-skills-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-skills application HTTP plane."

[lib]
name = "sdkwork_api_skills_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-intelligence-skills-repository-sqlx.workspace = true
sdkwork-intelligence-skills-service.workspace = true
sdkwork-skills-database-host.workspace = true
sdkwork-web-contract.workspace = true
serde_json.workspace = true
sdkwork-routes-skills-app-api.workspace = true
sdkwork-routes-skills-backend-api.workspace = true
