[package]
name = "sdkwork-routes-skills-app-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
sdkwork-intelligence-skills-service.workspace = true
sdkwork-routes-skills-common.workspace = true
sdkwork-skills-contract.workspace = true
sdkwork-web-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[lib]
path = "src/lib.rs"
